# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI Build (GitHub Nuget Feed)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Pack
      run: dotnet pack --configuration Release --output ./artifacts

    - name: Publish to GitHub Packages
      uses: actions/upload-artifact@v2
      with:
        name: Nuget Package
        path: ./artifacts/

    # Will only publish to GitHub hosted Nuget feed
    # If we are on the main branch (So PRs will not publish to it)
    - name: Add GitHub Nuget Feed
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget add source --username umbraco --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/umbraco/index.json"

    - name: Push to GitHub Nuget Feed
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github